# @name get all users
GET http://localhost:3000/users

###
# @name register user
POST http://localhost:3000/register
Content-Type: application/json

{
    "username" : "username",
    "password" : "password"
}

###
# @name login user
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "username",
    "password" : "password"
}
