version: "3.9"

services:
  postgres:
    image: postgres:latest 
    container_name: postgres_container
    environment:
      POSTGRES_USER: <your_username>
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: <your_db_name>
    ports:
      - "5432:5432" 
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

